name: EfficientParsing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: '11'
    - name: Install dependencies
      run: |
        sudo apt install gcc python3-dev default-libmysqlclient-dev build-essential libpq-dev
        pip install --upgrade pip
        pip install flake8
        pip install pytest
        pip install -r requirements.txt
        pip install depccg
        python -m nltk.downloader all
        pip install -e .
        pip install -U sphinx
        pip install -U sphinx-autoapi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 ./efficient_parsing ./test --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 ./efficient_parsing ./test --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - uses: actions/upload-artifact@v2
      with:
        name: test-artifacts
        path: res/test
    - name: Test with pytest
      run: |
        # we deselect abstractor tests because they require a server to be started which doesn't to work here
        pytest -k "not abstractor"
